spring:
  datasource:
    postgres-qa:
        username: qa
        password: 123
        host: localhost
        port: 5432
        db-name: fighter1
        jdbc-url: jdbc:postgresql://localhost:5432/fighter1
    postgres-dev:
        username: dev
        password: 1234
        host: localhost
        port: 5432
        db-name: fighter1
        jdbc-url: jdbc:postgresql://localhost:5432/fighter2
server:
  port: 8080
