spring:
  datasource:
    postgres-qa:
      username: qa
      password: 123
      host: localhost
      port: 5432
      db-name: frontend
      jdbc-url: jdbc:postgresql://localhost:5432/frontend
server:
  port: 8080
